language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

env:
  global:
    - DEFAULT=1
    - PHPSTAN=0

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: PHPCS=1
    - php: 7.0
      env: CODECOVERAGE=1 DEFAULT=0
    - php: 7.1
      env: PHPSTAN=1

install:
  - composer install --prefer-dist --no-interaction

before_script:
  - phpenv rehash
  - set +H

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then composer test; fi"
  - sh -c "if [ '$PHPSTAN' = '1' ]; then composer require --dev "phpstan/phpstan:^0.10" && composer phpstan; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then composer cs-check; fi"
  - sh -c "if [ '$CODECOVERAGE' = '1' ]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=clover.xml || true; fi"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
notifications:
  email: false
